name = "a0b_atsam3x8e_tc5_timer"
description = "A0B ATSAM3X8E High Resulotion Timer on top of TC5"
version = "0.1.0-dev"

authors = ["Vadim Godunko"]
maintainers = ["Vadim Godunko <vgodunko@gmail.com>"]
maintainers-logins = ["godunko"]
licenses = "Apache-2.0 WITH LLVM-exception"
tags = ["embedded", "timer"]

project-files = ["gnat/a0b_timer_platform.gpr"]
provides = ["a0b_timer_platform=0.1.0"]

[configuration]
disabled = true

[[depends-on]]
a0b_base = "*"
a0b_atsam3x8e = "*"
